# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

-   repo: local
    hooks:
    -   id: pytest-coverage
        name: pytest coverage
        entry: uv run pytest --cov=pymahjongutil --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
default_language_version:
  python: python3.13
